version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rock4me
      MYSQL_DATABASE: dnx
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - general-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - general-network

  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html
    networks:
      - general-network

networks:
  general-network:
    driver: bridge

volumes:
  mysqldata:
